<%!
 current_ = 'publications' 
%>
<%inherit file="_templates/site.mako" />
<h1>Publications</h1>
<h2>Papers</h2>
<ul class="bib">
	<li>Jinghe Zhang, Greg Welch, and Gary Bishop (2011). Reduced Measurement-Space Dynamic State Estimation (REMEDYSE) for Power Systems. To appear in PowerTech, 2011 IEEE Trondheim (Trondheim, Norway), 19–23 June 2011.</li>
	<li>Jinghe Zhang, Greg Welch, Gary Bishop, and Zhenyu Huang (2010). <a href="http://www.cs.unc.edu/~welch/media/pdf/Zhang2010ab.pdf">Optimal PMU Placement Evaluation for Power System Dynamic State Estimation</a>. In Proceedings of IEEE PES Conference on Innovative Smart Grid Technologies Europe (ISGT 2010), Chalmers Lindholmen, Göteborg, Sweden, October 10–13, 2010.</li>
	<li>Jinghe Zhang, Greg Welch, and Gary Bishop (2010). <a href="http://www.cs.unc.edu/~welch/media/pdf/Zhang2010aa.pdf">Observability and Estimation Uncertainty Analysis for PMU Placement Alternatives</a>. In Proceedings of the 2010 North American Power Symposium (NAPS 2010), Arlington, TX, U.S.A., September 26–28, 2010.</li>
	<li>Peter Parente, Gary Bishop (2009), <a href="http://http://portal.acm.org/citation.cfm?doid=1520340.1520363">Out from behind the curtain: learning from a human auditory display</a>. CHI Extended Abstracts 2009: 2575-2584</li>
	<li>Aaron Block, James Anderson, and Gary Bishop (2005), <a href="http://www.cs.unc.edu/~block/papers/euro05b.pdf">Fine-Grained Task Reweighting on Multiprocessors</a>, Proceedings of the 11th <span class="caps">IEEE</span> International Conference on Embedded and Real-Time Computing Systems and Applications, Hong Kong, China, <span class="caps">IEEE</span> Computer Society Press, pp. 429–435, August 2005.</li>
	<li>Jay Fischer, Jeremy Cummings, Kalpit Desai, Leandra Vicci, Ben Wilde, Chris Weigle, Gary Bishop, Russell Taylor II, C.W. Davis, R.C. Boucher, Timothy O’Brien, and Richard Superfine (2005), <a href="http://scitation.aip.org/getabs/servlet/GetabsServlet?prog=normal&id=RSINAK000076000005053711000001&idtype=cvips&gifs=yes">Three-dimensional force microscope: A nanometric optical tracking and magnetic manipulation system for the biomedical sciences</a>, Review of Scientific Instruments, 76, 053711, 11 pages.</li>
	<li>Peter Parente and Gary Bishop (2003), <a href="http://www.cs.unc.edu/Research/assist/bats/papers/BATS.pdf"><span class="caps">BATS</span>: The Blind Audio Tactile Mapping System</a> , in Proceedings of <span class="caps">ACMSE</span> 2003.</li>
	<li>Richard Superfine, Gary Bishop, Jeremy Cummings, Jay Fisher, G. Matthews, D. Sill, Russell Taylor II, Leandra Vicci, Chris Weigle, Greg Welch, and Ben Wilde (2002), <a href="http://www.cs.unc.edu/Research/nano/documentarchive/publications/2002_Superfine%20Touch%203DFM%20abstct.pdf">Touching in Biological Systems: A 3D Force Microscope</a>, Proceedings of Microscopy and Microanalysis (Quebec City, Canada).</li>
	<li>Dorian Miller and Gary Bishop (2002), <a href="http://www.cs.unc.edu/~tracker/proj/lm/latencymeter.pdf">Latency meter: a device for easily monitoring VE delay</a> , Proceedings of the <span class="caps">SPIE</span> Engineering Reality of Virtual Reality (San Jose, CA).</li>
	<li>Ruigang Yang, Greg Welch, and Gary Bishop (2002), <a href="http://www.cs.unc.edu/~welch/media/pdf/Yang_PG2002.pdf">Real-Time Consensus-Based Scene Reconstruction Using Commodity Graphics Hardware</a> , Pacific Conference on Computer Graphics and Applications 2002, pp. 225–235.</li>
	<li>Simon Julier and Gary Bishop (2002), <em>Guest Editors’ Introduction: Tracking: How Hard Can It Be?</em>, <span class="caps">IEEE</span> Computer Graphics and Applications 22(6), pp. 22–23.</li>
	<li>Greg Welch and Gary Bishop (2001), <a href="http://www.cs.unc.edu/~tracker/ref/s2001/kalman/index.html">An Introduction to the Kalman Filter</a>, <span class="caps">SIGGRAPH</span> 2001 course 8. In Computer Graphics, Annual Conference on Computer Graphics & Interactive Techniques. <span class="caps">ACM</span> Press, Addison-Wesley, Los Angeles, CA, <span class="caps">USA</span> (August 12–17), <span class="caps">SIGGRAPH</span> 2001 course pack edition.</li>
	<li>Bonnie Danette Allen, Gary Bishop, and Greg Welch (2001), <a href="http://www.cs.unc.edu/~tracker/ref/s2001/tracker/index.html">Tracking: Beyond 15 Minutes of Thought</a>, <span class="caps">SIGGRAPH</span> 2001 course 11. In Computer Graphics, Annual Conference on Computer Graphics & Interactive Techniques. <span class="caps">ACM</span> Press, Addison-Wesley, Los Angeles, CA, <span class="caps">USA</span> (August 12–17), <span class="caps">SIGGRAPH</span> 2001 course pack edition.</li>
	<li>Greg Welch, Gary Bishop, Leandra Vicci, Stephen Brumback, Kurtis Keller, and D’nardo Colucci (2001), <a href="http://www.cs.unc.edu/~tracker/media/pdf/Welch2001_HiBall_Presence.pdf">High-Performance Wide-Area Optical Tracking: The HiBall Tracking System</a>, Presence: Teleoperators and Virtual Environments 10(1): 1–21.</li>
	<li>Manuel Oliveira, Gary Bishop, and David McAllister (2000), <a href="http://www.cs.unc.edu/~gb/Pubs/RT.pdf">Relief Texture Mapping</a>, Proceedings of <span class="caps">SIGGRAPH</span> 00 (New Orleans, LA, July 23–27, 2000). In Computer Graphics Proceedings, Annual Conference Series, 2000, <span class="caps">ACM</span> <span class="caps">SIGGRAPH</span>, pp. 259–268.</li>
	<li>Gary Bishop and Greg Welch (2000), <a href="http://www.cs.unc.edu/~gb/Pubs/WorkingInTheOffice.pdf">Working the Office of Real Soon Now</a> , <span class="caps">IEEE</span> Computer Graphics and Applications, July-August 2000, pp. 76–78.</li>
	<li>Greg Welch, Gary Bishop, Leandra Vicci, Stephen Brumback, Kurtis Keller, and D’nardo Colucci (1999), <a href="http://www.cs.unc.edu/~welch/media/pdf/VRST99_HiBall.pdf">The HiBall Tracker: High-Performance Wide-Area Tracking for Virtual and Augmented Environments</a> , Proceedings of the <span class="caps">ACM</span> Symposium on Virtual Reality Software and Technology 1999 (VRST 99), University College London, December 20–22, 1999, pp. 1–10.</li>
	<li>Chun-Fa Chang, Gary Bishop, and Anselmo Lastra (1999), <a href="http://www.cs.unc.edu/~gb/Pubs/ldi_tree.pdf"><span class="caps">LDI</span> Tree: A Hierachical Representation for Image-based Rendering</a> , In Proceedings of <span class="caps">SIGGRAPH</span> 99 (Los Angeles, CA, August 8–13, 1999). In Computer Graphics Proceedings, Annual Conference Series, 1999, <span class="caps">ACM</span> <span class="caps">SIGGRAPH</span>, pp. 291–298.</li>
	<li>Lars Nyland, David McAllister, Voicu Popescu, Chris McCue, Anselmo Lastra, Paul Rademacher, Manuel Oliveira, Gary Bishop, Gopi Meenakshisundaram, Matt Cutts, and Henry Fuchs (1999), <a href="http://www.cs.unc.edu/~ibr/pubs/nyland-mview99/range_impact.pdf">The Impact of Dense Range Data on Computer Graphics</a> , Proceedings of Multi-View Modeling and Analysis Workshop (MVIEW99), (Part of CVPR99), (Fort Collins, CO), June 23–26, 1999.</li>
	<li>Manuel M. Oliveira and Gary Bishop (1999), <a href="http://www.cs.unc.edu/~ibr/pubs/oliveira-i3d99/ibo-paper.pdf">Image-Based Objects</a> , Proceedings of 1999 <span class="caps">ACM</span> Symposium on Interactive 3D Graphics, (Atlanta, Georgia), April 26–28, 1999, pp. 191–198.</li>
	<li>Ronald T. Azuma, Bruce R. Hoff, Howard E. Neely <span class="caps">III</span>, Ronald Sarfaty, Michael J. Daily, Gary Bishop, Vern Chi, Greg Welch, Ulrich Neumann, and Rich Nichols (1998), <a href="http://www.cs.unc.edu/~azuma/IWARpos.pdf">Making Augmented Reality Work Outdoors Requires Hybrid Tracking</a> , First International Workshop on Augmented Reality (IWAR’98), Associated workshop to <span class="caps">UIST</span> ‘98, November 1, 1998, San Francisco, CA, 6 pages.</li>
	<li>Paul Rademacher and Gary Bishop (1998), <a href="http://www.cs.unc.edu/~pxfl/papers/mcop98.pdf">Multiple-Center-of-Projection Images</a> , In Proceedings of <span class="caps">SIGGRAPH</span> 98 (Orlando, FL, July 20–27 1998). In Computer Graphics Proceedings Annual Conference Series, <span class="caps">ACM</span> <span class="caps">SIGGRAPH</span>.</li>
	<li>Greg Welch and Gary Bishop (1997), <a href="http://www.cs.unc.edu/~welch/media/pdf/scaat.pdf"><span class="caps">SCAAT</span>: Incremental Tracking with Incomplete Information</a> , In Proceedings of <span class="caps">SIGGRAPH</span> 97 (Los Angeles, CA, August 3–8 1997). In Computer Graphics Proceedings Annual Conference Series, <span class="caps">ACM</span> <span class="caps">SIGGRAPH</span>, pp. 333–344.</li>
	<li>William Mark and Gary Bishop (1997), <a href="http://www.cs.unc.edu/~ibr/pubs/mark-eghw/eghwpap-web.pdf">Memory Access Patterns of Occlusion-Compatible 3D Image Warping</a> , In Proceedings of the 1997 Siggraph/Eurographics Workshop on Graphics Hardware (Los Angeles, CA, August 3–4 1997), pp. 35–44.</li>
	<li>William Mark, Gary Bishop, and Leonard McMillan (1997), <a href="http://www.cs.unc.edu/~ibr/pubs/mark-i3d/i3dpaper-web.pdf">Post-Rendering 3D Warping</a> , Proceedings of 1997 Symposium on Interactive 3D Graphics (Providence, Rhode Island, April 27–30, 1997), pp. 7–16.</li>
	<li>Ronald Azuma and Gary Bishop (1995), <a href="http://www.cs.unc.edu/~gb/Pubs/s95azumabishop.pdf">A Frequency-Domain Analysis of Head-Motion Prediction</a> , In Proceedings of <span class="caps">SIGGRAPH</span> 95 (Los Angeles, CA, August 6–11 1995). In Computer Graphics Proceedings Annual Conference Series, <span class="caps">ACM</span> <span class="caps">SIGGRAPH</span>, pp. 401–408.</li>
	<li>Leonard McMillan and Gary Bishop (1995), <a href="http://www.cs.unc.edu/~gb/Pubs/p39-mcmillan.pdf">Plenoptic Modeling: An Image-Based Rendering System</a>, Proceedings of <span class="caps">SIGGRAPH</span> 95, Computer Graphics Proceedings, Annual Conference Series (August 1995, Los Angeles, California), pp. 39–46.</li>
	<li>Marc Olano, Jon Cohen, Mark Mine, and Gary Bishop (1995), <a href="http://www.cs.unc.edu/~olano/papers/latency/">Combatting Rendering Latency</a>, 1995 Symposium on Interactive 3D Graphics (Monterey, CA, April 9–12.</li>
	<li>Leonard McMillan and Gary Bishop (1995), <a href="http://www.cs.unc.edu/~mcmillan/papers/spie95_mcmillan.pdf">Head-Tracked Stereo Display Using Image Warping</a>, 1995 IS&T/SPIE Symposium on Electronic Imaging Science and Technology. <span class="caps">SPIE</span> Proceedings #2409A, (San Jose, CA. Feb 5–10, 1995), pp. 21–30.</li>
	<li>Henry Fuchs, Gary Bishop, Kevin Arthur, Leonard McMillan, Ruzena Bajcsy, Sang Lee, Hany Farid, and Takeo Kanade (1994), <a href="http://www.cs.unc.edu/~mcmillan/papers/mrcas94_fuchs.pdf">Virtual Space Teleconferencing Using a Sea of Cameras</a>, Proceedings of the First International Symposium on Medical Robotics and Computer Assisted Surgery, (Pittsburgh, PA.) Sept. 22–24, 1994.</li>
	<li>Ronald Azuma and Gary Bishop (1994), <a href="http://www.cs.unc.edu/~gb/Pubs/sig94AR.pdf">Improving Static and Dynamic Registration in an Optical See-through <span class="caps">HMD</span></a> , Proceedings of <span class="caps">SIGGRAPH</span> 94 (Orlando Florida, July 24–29, 1994). In Computer Graphics Proceedings, Annual Conference Series, 1994, <span class="caps">ACM</span> <span class="caps">SIGGRAPH</span>, pp. 197–204 + CD-ROM appendix.</li>
	<li>Gary Bishop, Henry Fuchs, Leonard McMillan, and Ellen Scher Zagier (1994), <a href="http://www.cs.unc.edu/~gb/Pubs/fless.pdf">Frameless Rendering: Double Buffering Considered Harmful</a> , Proceedings of <span class="caps">SIGGRAPH</span> 94, Computer Graphics Proceedings, Annual Conference Series (July 1994, Orlando, Florida), pp. 175–176.</li>
	<li>Russell Taylor, R.S. Williams, Vern Chi, Gary Bishop, J. Fletcher, Warren Robinett, and S. Washburn (1994), <a href="http://www.cs.unc.edu/Research/nano/documentarchive/talks/1994%20surface_abstract.pdf">Nanowelding: tip response during <span class="caps">STM</span> modification of Au surfaces</a>, Surface Science Letters 306, pp. L534-L538.</li>
	<li>Gary Bishop and Henry Fuchs (1992), <a href="http://www.cs.unc.edu/~gb/Pubs/92-027.pdf">Research Directions in Virtual Environments</a> , <span class="caps">ACM</span> Computer Graphics, vol. 26, no. 3, pp. 153–177.</li>
	<li>Jih-fang Wang, Ronald Azuma, Gary Bishop, Vern Chi, John Eyles, and Henry Fuchs (1990), <a href="http://www.cs.unc.edu/~gb/Pubs/WangOrlando.pdf">Tracking a head-mounted display in a room-sized environment with head-mounted cameras</a>, Proceeding: <span class="caps">SPIE</span>‘90 Technical Symposium on Optical Engineering & Photonics in Aerospace Sensing. Orlando, FL.</li>
	<li>Gary Bishop, Mark Monger, and Paul Ramsey (1990), <em>A Visualization Programming Environment for Multicomputers</em>, <span class="caps">IEEE</span> Computer Graphics and Applications, vol. 10, no. 4, pp. 50–59.</li>
	<li>Ken S. Roberts, Gary Bishop, and S.K. Ganapathy (1988), <em>Smooth Interpolation of Rotation Motions</em>, Computer Vision and Pattern Recognition, pp. 724–729.</li>
	<li>Gary Bishop and David M. Weimer (1986), <a href="http://www.cs.unc.edu/~gb/Pubs/siggraph86.html">Fast Phong Shading</a>, Computer Graphics (Proceedings of <span class="caps">SIGGRAPH</span> 86, August 1986, Dallas, Texas), 20(4), pp. 103–106.</li>
	<li>Gary Bishop and Henry Fuchs (1984), <em>The Self-Tracker: A Smart Optical Sensor on Silicon</em>, Proceedings, Conference on Advanced Research in <span class="caps">VLSI</span> at <span class="caps">MIT</span> (January 23–25, 1984), Artech House.</li>
</ul>
<h2>Patents</h2>
<ul class="bib">
	<li>Gary Bishop and Manuel Oliveira (2002), <a href="http://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO1&Sect2=HITOFF&d=PALL&p=1&u=%2Fnetahtml%2FPTO%2Fsrchnum.htm&r=1&f=G&l=50&s1=6,424,351.PN.&OS=PN/6,424,351&RS=PN/6,424,351">Method and Systems for Producing Three-Dimensional Images Using Relief Textures</a>, patent number 6,424,351.</li>
	<li>Henry Fuchs, Mark Livingston, Gary Bishop, and Greg Welch (1999), <a href="http://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO1&Sect2=HITOFF&d=PALL&p=1&u=%2Fnetahtml%2FPTO%2Fsrchnum.htm&r=1&f=G&l=50&s1=5,870,136.PN.&OS=PN/5,870,136&RS=PN/5,870,136">Dynamic Generation of Imperceptible Structured Light for Tracking and Acquisition of Three Dimensional Scene Geometry and Surface Characteristics in Interactive Three Dimensional Computer Graphics Applications</a>, patent number 5,870,136.</li>
	<li>Gary Bishop and John D. Austin (1990), <a href="http://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO1&Sect2=HITOFF&d=PALL&p=1&u=%2Fnetahtml%2FPTO%2Fsrchnum.htm&r=1&f=G&l=50&s1=4,910,683.PN.&OS=PN/4,910,683&RS=PN/4,910,683">Method and Apparatus for Fractional Double Buffering</a>, patent number 4,910,683.</li>
</ul>
<h2>Reports</h2>
<ul class="bib">
	<li>Manuel M. Oliveira and Gary Bishop (1999), <a href="http://www.cs.unc.edu/~gb/Pubs/99-015.pdf">Relief Textures</a>, <span class="caps">UNC</span> Computer Science Technical Report TR99–015, University of North Carolina, March 29, 1999.</li>
	<li>Manuel M. Oliveira and Gary Bishop (1999), <a href="http://www.cs.unc.edu/~gb/Pubs/99-002.pdf">Factoring 3-D Image Warping Equations into a Pre-Warp Followed by Conventional Texture Mapping</a> , <span class="caps">UNC</span> Computer Science Technichal Report TR99–002, University of North Carolina, January 15, 1999.</li>
	<li>Manuel M. Oliveira and Gary Bishop (1998), <a href="http://www.cs.unc.edu/~gb/Pubs/98-023.pdf">Dynamic Shading in Image-Based Rendering</a> , <span class="caps">UNC</span> Computer Science Technical Report TR98–023, University of North Carolina, May 31, 1998.</li>
	<li>William R. Mark and Gary Bishop (1998), <a href="http://www.cs.unc.edu/~gb/Pubs/98-011.pdf">Efficient Reconstruction Techniques for Post-Rendering 3D Image Warping</a> , <span class="caps">UNC</span> Computer Science Technical Report TR98–011, University of North Carolina, March 21, 1998, 15 pages.</li>
	<li>William Mark, Gary Bishop, and Leonard McMillan (1996), <a href="http://www.cs.unc.edu/~gb/Pubs/96-020.pdf">Post-Rendering Image Warping for Latency Compensation</a>, <span class="caps">UNC</span>-CH Computer Science Technical Report 96–020, 6 pages.</li>
	<li>Greg Welch and Gary Bishop (1995), <a href="http://www.cs.unc.edu/~welch/kalman/kalmanIntro.html">An Introduction to the Kalman Filter</a>, <span class="caps">UNC</span>-CH Computer Science Technical Report 95–041, 14 pages.</li>
	<li>Mark Mine and Gary Bishop (1993), <a href="http://www.cs.unc.edu/~gb/Pubs/93-005.pdf">Just-In-Time Pixels</a> , <span class="caps">UNC</span> Chapel Hill Computer Science Technical Report TR93–005.</li>
	<li>Gary Bishop (1987), <em>unc++ – restore C++ names for debugging</em>, AT&T Bell Laboratories Technical Memorandum.</li>
	<li>Gary Bishop (1986), <em>Synthetic Visual Environments</em>, AT&T Bell Laboratories Technical Memorandum.</li>
	<li>Eric Hoffert and Gary Bishop (1986), <em>Exact and Efficient Area Sampling Techniques for Spatial Antialiasing</em>, AT&T Bell Laboratories Technical Memorandum, 11 pages.</li>
	<li>Gary Bishop (1984), <a href="http://www.cs.unc.edu/~gb/Pubs/SelfTracker.pdf">The Self-Tracker: A Smart Optical Sensor on Silicon</a> , <span class="caps">UNC</span> Chapel Hill Computer Science Dissertation TR84–002, 61 pages.</li>
	<li>Gary Bishop (1982), <em>Gary’s Ikonas Assembler, Version 2; Differences Between Gia2 and C</em>, <span class="caps">UNC</span> Chapel Hill Computer Science Technical Report TR82–010.</li>
</ul>
